#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : unzip
Version  : 1
Release  : 22
URL      : ftp://ftp.info-zip.org/pub/infozip/src/unzip60.tgz
Source0  : ftp://ftp.info-zip.org/pub/infozip/src/unzip60.tgz
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-3-Clause
Requires: unzip-bin
Requires: unzip-doc
BuildRequires : qtbase-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}
Patch1: cve-2014-8139.patch
Patch2: cve-2014-8140.patch
Patch3: cve-2014-8141.patch
Patch4: cve-2014-9636.patch
Patch5: cve-2015-7696.patch
Patch6: cve-2015-7697.patch
Patch7: cve-2016-9844.patch
Patch8: cve-2014-9913.patch
Patch9: cve-2018-1000035.patch

%description
Info-ZIP group's portable UnZip zipfile-extraction program (and related
utilities).

%package bin
Summary: bin components for the unzip package.
Group: Binaries

%description bin
bin components for the unzip package.


%package doc
Summary: doc components for the unzip package.
Group: Documentation

%description doc
doc components for the unzip package.


%prep
%setup -q -n unzip60
%patch1 -p1
%patch2 -p1
%patch3 -p1
%patch4 -p1
%patch5 -p1
%patch6 -p1
%patch7 -p1
%patch8 -p1
%patch9 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1522794460
export CFLAGS="$CFLAGS -fstack-protector-strong -mzero-caller-saved-regs "
export FCFLAGS="$CFLAGS -fstack-protector-strong -mzero-caller-saved-regs "
export FFLAGS="$CFLAGS -fstack-protector-strong -mzero-caller-saved-regs "
export CXXFLAGS="$CXXFLAGS -fstack-protector-strong -mzero-caller-saved-regs "
make  %{?_smp_mflags} -f unix/Makefile STRIP="" generic

%install
export SOURCE_DATE_EPOCH=1522794460
rm -rf %{buildroot}
make || make -f unix/Makefile install prefix=%{buildroot}/usr
## make_install_append content
mkdir -p %{buildroot}/usr/share/man
mv %{buildroot}/usr/man/*  %{buildroot}/usr/share/man/
rmdir %{buildroot}%{_prefix}/man/
## make_install_append end

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/funzip
/usr/bin/unzip
/usr/bin/unzipsfx
/usr/bin/zipgrep
/usr/bin/zipinfo

%files doc
%defattr(-,root,root,-)
%doc /usr/share/man/man1/*
