#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : unzip
Version  : 6.0
Release  : 25
URL      : https://sourceforge.net/projects/infozip/files/UnZip%206.x%20%28latest%29/UnZip%206.0/unzip60.tar.gz
Source0  : https://sourceforge.net/projects/infozip/files/UnZip%206.x%20%28latest%29/UnZip%206.0/unzip60.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-3-Clause
Requires: unzip-bin = %{version}-%{release}
Requires: unzip-license = %{version}-%{release}
Requires: unzip-man = %{version}-%{release}
BuildRequires : buildreq-qmake
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}
Patch1: cve-2014-8139.patch
Patch2: cve-2014-8140.patch
Patch3: cve-2014-8141.patch
Patch4: cve-2014-9636.patch
Patch5: cve-2015-7696.patch
Patch6: cve-2015-7697.patch
Patch7: cve-2016-9844.patch
Patch8: cve-2014-9913.patch
Patch9: cve-2018-1000035.patch
Patch10: CVE-2018-18384.patch
Patch11: CVE-2019-13232.patch

%description
Info-ZIP group's portable UnZip zipfile-extraction program (and related
utilities).

%package bin
Summary: bin components for the unzip package.
Group: Binaries
Requires: unzip-license = %{version}-%{release}

%description bin
bin components for the unzip package.


%package license
Summary: license components for the unzip package.
Group: Default

%description license
license components for the unzip package.


%package man
Summary: man components for the unzip package.
Group: Default

%description man
man components for the unzip package.


%prep
%setup -q -n unzip60
%patch1 -p1
%patch2 -p1
%patch3 -p1
%patch4 -p1
%patch5 -p1
%patch6 -p1
%patch7 -p1
%patch8 -p1
%patch9 -p1
%patch10 -p1
%patch11 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1563919242
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto -fstack-protector-strong -mzero-caller-saved-regs=used "
export FCFLAGS="$CFLAGS -fno-lto -fstack-protector-strong -mzero-caller-saved-regs=used "
export FFLAGS="$CFLAGS -fno-lto -fstack-protector-strong -mzero-caller-saved-regs=used "
export CXXFLAGS="$CXXFLAGS -fno-lto -fstack-protector-strong -mzero-caller-saved-regs=used "
make  %{?_smp_mflags} -f unix/Makefile STRIP="" generic


%install
export SOURCE_DATE_EPOCH=1563919242
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/unzip
cp LICENSE %{buildroot}/usr/share/package-licenses/unzip/LICENSE
make || make -f unix/Makefile install prefix=%{buildroot}/usr
## install_append content
mkdir -p %{buildroot}/usr/share/man
mv %{buildroot}/usr/man/*  %{buildroot}/usr/share/man/
rmdir %{buildroot}%{_prefix}/man/
## install_append end

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/funzip
/usr/bin/unzip
/usr/bin/unzipsfx
/usr/bin/zipgrep
/usr/bin/zipinfo

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/unzip/LICENSE

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/funzip.1
/usr/share/man/man1/unzip.1
/usr/share/man/man1/unzipsfx.1
/usr/share/man/man1/zipgrep.1
/usr/share/man/man1/zipinfo.1
